### PR TITLE
Only display headers when there is data to display

### PR DESCRIPTION
**Pull request by mngo33**
Only render "What You'll Do" and "Requirements" headers when there is data to display

### CODE REVIEW

**Comment by eevanwong** [comment]
Make sure to add pictures to show it working.

**Comment by mngo33** [comment]
When there is data to show under "What you'll do:" and "Requirements" headings:
withdata

No data to show under "What you'll do:" and "Requirements" headings:
nodata

**Review by eevanwong — APPROVED** [review]
LGTM

**Comment by mngo33** [comment]
Ticket link: [https://app.clickup.com/t/1ehr8q6](url)

**Pull request merged**
