### PR TITLE
Past geese timeline component

### PR DESCRIPTION
**Pull request by Quinn1876**
Just needs a Readme

### CODE REVIEW

**Comment by jxrin** [comment]
@Quinn is the 'waterloop-site/src/api/imgs.ts' folder required for this component? I don't think it's being used anywhere

**Comment by Quinn1876** [comment]
> 
> 
> @quinn is the 'waterloop-site/src/api/imgs.ts' folder required for this component? I don't think it's being used anywhere

It is not, I'll get rid of it

**Comment by Quinn1876** [comment]
@jxrin Should be good for final pass

**Comment by jxrin** [comment]
Tysm will review and merge in today :)

**Comment by Quinn1876** [comment]
@jxrin  Everything should be working now

**Pull request merged**
